### ISSUE TITLE
Can't move window

### ISSUE THREAD

**Issue by 1scfz** [use-arcfox/arcfox#11]
I installed it using the steps but I just can't move my window like I used to be able to using the top border and dragging... Is there a special spot that I don't know about or is this a glitch? I'm using Parrot Security OS KDE, i5 10th gen 8GB RAM laptop

**Comment by LuanderFarias** [comment]
You should be able to do it. The sidebar actually still on the same place as normal firefox, it's only invisible.... can you send me a video of you trying?

My discord handle: Mono#3608

**Comment by LuanderFarias** [comment]
@1scfz Just tried ParrotOS security and arcfox. It's actually a real problem and idk why it's happening. But you can still try arcfox, some time ago i developed the new arcfox theme (still under dev) and it adds a way to move the window that works on parrot! it's on the theme dev builds repo.

theme dev builds:
https://github.com/use-arcfox/arcfox-theme

It's not the best solution cause it's looks so more strange than in windows, but it's a way to move the window at the moment. Someday i will try to solve it or maybe even divide the themes based on the OS. ty for showing me this problem.
