### ISSUE TITLE
Close button doesnt show on long tab names

### ISSUE THREAD

**Issue by Henry-Hiles** [use-arcfox/arcfox#15]
As the title suggests, the close button does not seem to show on long tab names
![image](https://user-images.githubusercontent.com/71790868/232874834-f8353362-6d26-4d76-9347-c85230e1984d.png)

**Comment by LuanderFarias** [comment]
need to adjust the tab title to not overflox-x, ty for the feedback.

**Comment by Henry-Hiles** [comment]
This seems to be fixed.
