### ISSUE TITLE
Use user's search engine

### ISSUE THREAD

**Issue by Henry-Hiles** [use-arcfox/arcfox#18]
Hello! It would be great if the users search engine would be used instead of google, which many prefer not to use for privacy reasons. Thanks!

**Comment by Henry-Hiles** [comment]
If this is already a feature then sorry, I couldn't find anything though.

**Comment by LuanderFarias** [comment]
Nice Feature!!! It's already on the roadmap, tysm for the suggestion :)

**Comment by Henry-Hiles** [comment]
Great, thanks! If this is already on the roadmap would you like me to close this issue?

**Comment by LuanderFarias** [comment]
No need to, it's actually good to have this here cause i remember to do it :)

**Comment by Henry-Hiles** [comment]
Sounds good! This is the only thing stopping me from using ArcFox so hope its added soon! If you need help I could look at making a PR if you want.

**Comment by LuanderFarias** [comment]
I'm gonna try to add it on the next update but feel free to do a PR, it would be incredible :)

**Comment by Henry-Hiles** [comment]
I'll take a look this weekend, but I'm not sure as I've never made a web extension.

**Comment by Henry-Hiles** [comment]
I'm trying to do it now. Do you have a Discord account where I can ask you some questions?

**Comment by LuanderFarias** [comment]
TYSM FOR THE PR!! great feature 🙏🏼

**Comment by Henry-Hiles** [comment]
No problem! I have some questions, do you have a Discord account I can contact you at, or should i just make some GitHub issues? Discord would be easier if you have one.

**Comment by LuanderFarias** [comment]
Arcfox have a discord server, it's on the README at support section

**Comment by Henry-Hiles** [comment]
Oh, thanks, no idea how I didn't see that!
