### ISSUE TITLE
Show navigation toolbar on hover

### ISSUE THREAD

**Issue by rago666** [use-arcfox/arcfox#2]
Currently navigation toolbar is hidden. This makes working with extensions impossible. It would be pretty nice if navigation toolbar is exposed on hover like arc does it.

**Comment by LuanderFarias** [comment]
Arc does that? sorry, i never tried arc so i didn't know that. But i know that can be done with arcfox-theme! gonna try to develop it soon...

**Comment by rago666** [comment]
Yes. 
![Screenshot from 2023-03-18 17-29-01](https://user-images.githubusercontent.com/51720144/226109935-d179f7ff-6131-4ea5-a960-ad261dd6098d.png)

**Comment by LuanderFarias** [comment]
oh, tysm for showing me. Gonna add it when i can :)

**Comment by LuanderFarias** [comment]
@rago666 Done! The update is coming soon on the developement build of the theme! [dev build](https://github.com/use-arcfox/arcfox-theme)
