### ISSUE TITLE
Alt+Q doesn't work on both Windows and Arch Linux

### ISSUE THREAD

**Issue by Vincent-vst** [use-arcfox/arcfox#20]
cf :  https://github.com/use-arcfox/arcfox/blob/1b22f9190e8d9cb80a85b32de927abb78ad74778/core/manifest.json#L28     

I tried on both Windows 10 and Arch and it didn't work.    
I will mess around with  `manifest.json` or with `core/src/background.js`  to see if I can fix it.   
Dunno if I'm the only one with this issue...

**Comment by Vincent-vst** [comment]
I removed any other extension that could mess with it. I also changed the shortcut to a different one with no success.    
I put a console.log in `handleShortcut()` to debug. And it worked, the function is called but nothing happens.

**Comment by LuanderFarias** [comment]
sorry, that's one of the last things i added so i didn't tested in other systems... also, TYSM for fixing it :)
