### ISSUE TITLE
open a link in a new tab does not update sidebar

### ISSUE THREAD

**Issue by Vincent-vst** [use-arcfox/arcfox#22]
It's something that I noticed but have no idea how to fix it.     
Basically when I open a link in a new tab, the sidebar does not get updated.    
In order to see it, I have to manually add a new tab and then two tabs will automaticaly pop off : my link and the new tab I just added.

**Comment by LuanderFarias** [comment]
i noticed that!! and even commented on arcfox server. i'm fixing it :)

**Comment by LuanderFarias** [comment]
FIXED!! Coming on the next update!! sorry for taking so much time for it...
