### ISSUE TITLE
Close Button Hidden Sometime.

### ISSUE THREAD

**Issue by toonnongaeoy** [use-arcfox/arcfox#23]
Sometime the Tab Close Button was hidden. But it still show for some second and it's go away

![image](https://user-images.githubusercontent.com/82090464/235375494-49b593de-0323-4d7c-9231-7a7492632f05.png)

[Here a video when the Close Tab Button appears for some seconds.](https://cloud-fagant1ss-hack-club-bot.vercel.app/0screencast_from_2023-05-01_03-46-51.webm)

**Comment by LuanderFarias** [comment]
the close tab icon is hidden cause some of your tabs have big names. it's a problem i'm working out, gonna close this problem but you will know when i fix it cause i'm gonna close #15 issue. tysm for sharing!

**Comment by toonnongaeoy** [comment]
For me, it still happen.
![image](https://user-images.githubusercontent.com/82090464/236356142-289c2324-97d8-4558-98ff-cf98e3263a30.png)

**Comment by LuanderFarias** [comment]
ik, it's not fixed yet.

**Comment by toonnongaeoy** [comment]
Oh. Maybe I use older version of userChrome.css. Let me update it first.

**Comment by LuanderFarias** [comment]
gonna re-open this cause the other is closed so...

**Comment by LuanderFarias** [comment]
> Oh. Maybe I use older version of userChrome.css. Let me update it first.

oh, ok... pls keep me updated

**Comment by toonnongaeoy** [comment]
I use [this one.](https://github.com/use-arcfox/arcfox-theme/blob/main/userChrome.css) Maybe update would help.

**Comment by LuanderFarias** [comment]
that's the last code.... it's prolly a problem with the extension itself. gonna fix asap. tysm for the feedback and for testing.

**Comment by toonnongaeoy** [comment]
And yep. It still does. I will waiting for the update.

![image](https://user-images.githubusercontent.com/82090464/236360934-fea777b5-a941-4e02-af44-c17f2a5f722e.png)

**Comment by LuanderFarias** [comment]
FIXED!! Coming on the next update 👍🏼
