### ISSUE TITLE
Rounded corners in fullscreen

### ISSUE THREAD

**Issue by DeadFrostt** [use-arcfox/arcfox#26]
![image](https://github.com/use-arcfox/arcfox/assets/71704732/4af92b23-08e5-4152-81a3-4f392528e6f4)

Fullscreen isnt actually fullscreen the corners are rounded which gives it an unsettling look.

**Comment by LuanderFarias** [comment]
i know, that is unfortunally unfixable, since the only way to modify firefox ui is with userchrome.css and it only runs on the startup so i can't do things like remove this border when i go fullscreen (and yes, i tried a lot)... sorry, but i think i'm not gonna fix that soon :(

**Comment by LuanderFarias** [comment]
i was scrolling through the closed issues and damn..... this was solved like a week later lol
