### ISSUE TITLE
Title Bar Buttons only update fill color on hover

### ISSUE THREAD

**Issue by glennDittmann** [use-arcfox/arcfox#27]
Hey,
first of all great project. I really like the idea of having an arc like workflow within the open source firefox context.

So.. when I hover over the three little buttons in the top left corner, to either _close_, _minimize_ or _expand_ the window, they only update their fill color to a brighter grey. The functionality works flawless though.

Expected: change color and icon similar looking to safari, to indicate button behavior.

On Pop!_OS 22.04

**Comment by LuanderFarias** [comment]
NICE FEATURE!! i never knew safari does that! gonna sure implement it :)
