### ISSUE TITLE
How to open side bar

### ISSUE THREAD

**Issue by Vincent-vst** [use-arcfox/arcfox#3]
This is a brilliant work !   
Everything work nicely.    
But I don't know how to open the ArcFox side bar once I close it.    
There's probably a shortcut I'm missing.   
(by side bar, I mean the bar where I can navigate between my tabs)

**Comment by LuanderFarias** [comment]
I'm developing the shortcut, it was something i missed out while developing...

**Comment by LuanderFarias** [comment]
@Vincent-vst Done!! theres a new arcfox update coming soon that have this function using "Alt+Q"!
