### ISSUE TITLE
Uninstalling arcfox

### ISSUE THREAD

**Issue by frimdo** [use-arcfox/arcfox#31]
Hi, I tried to install Arcfox addon with the theme according to the manual. I was disappointed to see, that the addon is in early stage of development (missing spaces, no way to drag the window,...). Now, I would like to uninstall the addon. But after uninstalling, the firefox is broken (looks like arcfox without the left tab). 
Is there something I am missing?

I tried:
uninstalling addon -> removing css file -> disabling Customizations.stylesheets
uninstalling addon -> disabling Customizations.stylesheets -> removing css file
disabling Customizations.stylesheets -> removing css file -> uninstalling addon

With Firefox restart between each step. 
Please, help me get firefox back to default.

**Comment by Henry-Hiles** [comment]
All you need to do is delete the `chrome` folder and uninstall the add-on. I've done it before, works fine for me.

**Comment by frimdo** [comment]
This did not work for me, but I managed to run firefox without addons (about:support -> troubleshoot mode) and in this I deleted startup cache (about:support -> clear startup cache). 

This did the job.

Thanks
