### ISSUE TITLE
Defined Keymaps

### ISSUE THREAD

**Issue by AlephaNull** [use-arcfox/arcfox#32]
Going to make the switch from Brave. Awesome Stuff. Maybe I'm just an idiot but I can't for the life of me figure out the keyboard shortcuts. 
Do I use standard firefox keymaps? Are there custom keymaps? Maybe a nice wiki would help. (I'd be willing to write it)

Asking because I can't get out of the history window in the sidebar. No matter what I press, I can't go back to the home sidebar.

Please and Thanks. It's likely I'm just missing something.

**Comment by Vincent-vst** [comment]
Try `alt+q` to open and close the side bar.    
You can find this shortcut in the manifest.json line 30. https://github.com/use-arcfox/arcfox/blob/d5006c10a7cf17e16d3a46a6aab5f46d18d2111f/core/manifest.json#L30   
But I agree, a wiki (or at least something in the readme) would be great.

**Comment by LuanderFarias** [comment]
Hey, sorry for the late response. There's actually supposed to have a documentation with that kind of information, but i did not started it :)

**Comment by AlephaNull** [comment]
Thank You for resolving my query! Works great now. If you need help with writing the docs, hit me up on any of my socials. I'd do it without pay.

**Comment by AlephaNull** [comment]
Thank You for resolving my query! Works great now. If you need help with writing the docs, hit me up on any of my socials. I'd do it without pay.
