### ISSUE TITLE
Sidebar doesn't reflect tab being closed when using CTRL+W hotkey to close current tab

### ISSUE THREAD

**Issue by ayyvr** [use-arcfox/arcfox#34]
Tabs closed with CTRL+W hotkey remain visible in sidebar. 
They can be removed from view with the x button.

**Comment by Danielduel** [comment]
@ayyvr  if you have setup to do this - feel free to test my PR ^

**Comment by LuanderFarias** [comment]
Fixed on the new PR (release coming asap)
