### ISSUE TITLE
Discord link in README doesn't work

### ISSUE THREAD

**Issue by Danielduel** [use-arcfox/arcfox#36]
As in the topic, do you form sort of community around this project?

**Comment by LuanderFarias** [comment]
i just forgot to update it. sorry, gonna update asap

**Comment by Danielduel** [comment]
Hello @LuanderFarias, I think it wasn't pushed yet, could you reiterate on it please?

**Comment by LuanderFarias** [comment]
i forgot to update again, updated :p
