### ISSUE TITLE
Fullscreen videos have border around them.

### ISSUE THREAD

**Issue by rago666** [use-arcfox/arcfox#5]
The border doesn't disappear in full screen windows. 

![Screenshot from 2023-03-19 01-02-15](https://user-images.githubusercontent.com/51720144/226131189-6d477a50-68dd-4ca5-8ad7-bfa04684d725.png)

**Comment by LuanderFarias** [comment]
At the moment i did the border be on the browser window, that's probably the problem. Gonna fix it soon, tysm!

**Comment by LuanderFarias** [comment]
I think i found a solution! instead of using userChrome.css to add the border i'm gonna do a script that runs on the extension and change the css of the current website adding a padding and the border. It also gonna help on when i do the themes :)
