### ISSUE TITLE
No round border on the right side of browser window?

### ISSUE THREAD

**Issue by RangHo** [use-arcfox/arcfox#6]
At the moment, there is no rounding on the right side. Is this intentional design choice? It kinda bugs me that the left and the right side is not balanced...

I currently have modified the `userChrome.css` file, and the `diff` out is shown below:

```diff
29a30,31
>   border-top-right-radius: 10px;
>   border-bottom-right-radius: 10px;
51c53
< }
\ No newline at end of file
---
> }
```

Anyways, thanks for the extension, and I look forward to the official v1.0 release!

**Comment by Vincent-vst** [comment]
yeah, i noticed this as well. Are you gonna submit a pull request ?

**Comment by LuanderFarias** [comment]
It's intentional. cause in windows i can't round the full window... so the right browser rounded looked a bit strange to me, but i can change it :)
