### ISSUE TITLE
Add support for middle click to close tabs

### ISSUE THREAD

**Issue by 0xCUB3** [use-arcfox/arcfox#9]
On mice, if you click the scroll wheel, on basically every browser, it will close the tab that you are hovering over. Would be a cool addition!

**Comment by LuanderFarias** [comment]
Nice feature!! gonna add it soon. Also ty @Vincent-vst for the code! you always help a lot, if you want to do a pr with that update i'm gonna thankfully approve it! than you name can be marked on this repo :)

**Comment by Vincent-vst** [comment]
:+1: ok, I'm working on it !

**Comment by LuanderFarias** [comment]
oh yeah, sorry.

**Comment by LuanderFarias** [comment]
gonna reopen this cause this is a problem that get back in this new version :(

**Comment by LuanderFarias** [comment]
Fixed again!! coming on the next update :)
